### ISSUE TITLE
Tracker never turns off (sleeps)

### ISSUE THREAD

**Issue by jschwalbe** [dmiddlecamp/fancy-asset-tracker#6]
I'm VERY new to this stuff, so please bear with me. I've managed to flash the motion-tracker-pro to my electron. It works pretty well. I get plenty of trk/dev and trk/enc and trk/loc messages, but they don't seem to stop. The device has been sitting in my car undisturbed for the past 3 hours and it's still churning out data every 60 seconds.

Any ideas?  Thanks!

**Comment by dmiddlecamp** [comment]
Hi @jschwalbe ,

  Sorry about that!  Sometimes I tweak these projects from time to time when I'm deploying them, and behavior can change.  I think the sleep behavior might be commented out right now, checkout these lines:

https://github.com/dmiddlecamp/fancy-asset-tracker/blob/master/motion-tracker-pro/main.ino#L175

Thanks,
David

**Comment by jschwalbe** [comment]
Stellar. Working great! Thanks :)

**Comment by jschwalbe** [comment]
Not sure if you'll get this since I closed the issue, but I think there's another reason it's not sleeping:
```
if (lastMotion > now) { lastMotion = now; }
```
happens _every single loop_, so `if ((now - lastMotion) > NO_MOTION_IDLE_SLEEP_DELAY) ` is never true so it never goes to sleep!
